# Generated by Django 5.1.7 on 2025-03-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='defaults/default_product.jpg', upload_to='photos/products/'),
        ),
    ]
