# Generated by Django 5.1.7 on 2025-04-14 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-date_added',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
