# Generated by Django 5.1.7 on 2025-04-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('USA', 'United States'), ('Canada', 'Canada'), ('UK', 'United Kingdom'), ('Australia', 'Australia'), ('India', 'India'), ('France', 'France'), ('Germany', 'Germany'), ('Italy', 'Italy'), ('Spain', 'Spain'), ('Brazil', 'Brazil'), ('Other', 'Other')], default='USA', max_length=100),
        ),
    ]
